name: Testing direkt vid push.

on: push

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd Backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd Frontend
          npm install

      - name: Start backend
        run: |
          cd Backend
          npm run dev &

        env:
          PGURI: ${{ secrets.PGURI }}

      - name: Start frontend
        run: |
          cd Frontend
          npm run dev &

      - name: Run Cypress E2E and Cucumber tests
        run: |
          cd Frontend
          npx cypress run

      - name: Run Cypress component test
        run: |
          cd Frontend
          npx cypress run --component
